@ECHO OFF
:WELCOME
ECHO LOADING ALPHA'S MULTI-QT OPENER...
timeout 10

:DIR_MOVE
ECHO MOVING TO SPECIFIED QT-DIR...
cd C:\Users\your_user_here\Desktop\Wallets
timeout 10

:RVN
CHOICE /C YNC /N /M "OPEN RVN QT-WALLET? Y/N OR C TO CANCEL"%1
IF %ERRORLEVEL%==1 GOTO RVN_YES
IF %ERRORLEVEL%==2 GOTO RVN_NO
IF %ERRORLEVEL%==3 GOTO CANCEL

:RVN_YES
ECHO OPENING RVN-QT...
cd C:\Users\your_user_here\Desktop\Wallets\raven-4.3.2.1\bin
START raven-qt.exe 
timeout 10
GOTO RITO

:RVN_NO
ECHO RVN-QT NOT OPENED...
timeout 10
GOTO RITO

:RITO
CHOICE /C YNC /N /M "OPEN RITO QT-WALLET? Y/N OR C TO CANCEL"%1
IF %ERRORLEVEL%==1 GOTO RITO_YES
IF %ERRORLEVEL%==2 GOTO RITO_NO
IF %ERRORLEVEL%==3 GOTO CANCEL

:RITO_YES
ECHO OPENING RITO-QT... 
cd C:\Users\your_user_here\Desktop\Wallets\rito-2.4.2.0\bin
START rito-qt.exe
timeout 10
GOTO PGN

:RITO_NO
ECHO RITO-QT NOT OPENED...
timeout 10
GOTO PGN

:PGN
CHOICE /C YNC /N /M "OPEN PGN QT-WALLET? Y/N OR C TO CANCEL"%1
IF %ERRORLEVEL%==1 GOTO PGN_YES
IF %ERRORLEVEL%==2 GOTO PGN_NO
IF %ERRORLEVEL%==3 GOTO CANCEL

:PGN_YES
ECHO OPENING PGN-QT... 
cd C:\Users\your_user_here\Desktop\Wallets\pigeon-build
START pigeon-qt.exe
timeout 10
GOTO RTM

:PGN_NO
ECHO PGN-QT NOT OPENED...
timeout 10
GOTO RTM

:RTM
CHOICE /C YNC /N /M "OPEN RTM QT-WALLET? Y/N OR C TO CANCEL"%1
IF %ERRORLEVEL%==1 GOTO RTM_YES
IF %ERRORLEVEL%==2 GOTO RTM_NO
IF %ERRORLEVEL%==3 GOTO CANCEL

:RTM_YES
ECHO OPENING RTM-QT...
cd C:\Users\your_user_here\Desktop\Wallets\raptoreum-build
START raptoreum-qt.exe
timeout 10
GOTO AVN

:RTM_NO
ECHO RTM-QT NOT OPENED...
timeout 10
GOTO AVN

:AVN
CHOICE /C YNC /N /M "OPEN AVN QT-WALLET? Y/N OR C TO CANCEL"%1
IF %ERRORLEVEL%==1 GOTO AVN_YES
IF %ERRORLEVEL%==2 GOTO AVN_NO
IF %ERRORLEVEL%==3 GOTO CANCEL

:AVN_YES
ECHO OPENING AVN-QT... 
cd C:\Users\your_user_here\Desktop\Wallets\AVN x86_64-win 3.1.1
START avian-qt.exe
timeout 10
GOTO END

:AVN_NO
ECHO AVN-QT NOT OPENED...
timeout 10
GOTO END

:CANCEL
ECHO PROCESS CANCELED!
ECHO THANKS FOR USING!!!
timeout 10
exit

:END
ECHO "BE PATIENT AND LET THE BLOCK INDEXES LOAD!!!"
timeout 60
ECHO "LOADING COMPLETE... MULTI-QT OPENER SUCCESSFUL! ENJOY AND KEEP THOSE KEYS SAFE!!!"
timeout 10
exit